/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: jackbaeten (https://sketchfab.com/jackbaeten)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/macbook-pro-m3-16-inch-2024-8e34fc2b303144f78490007d91ff57c4
Title: macbook pro M3 16 inch 2024
*/

import {useGLTF, useTexture} from '@react-three/drei'
import type { ThreeElements } from '@react-three/fiber'
import * as THREE from 'three'
import type { GLTF } from 'three-stdlib'
import useMacbookStore from "../../store";
import {useEffect} from "react";
import {noChangeParts} from "../../../public/constants.ts";
import {Color} from "three";

type GLTFResult = GLTF & {
    nodes: {
        Object_10: THREE.Mesh
        Object_16: THREE.Mesh
        Object_20: THREE.Mesh
        Object_22: THREE.Mesh
        Object_30: THREE.Mesh
        Object_32: THREE.Mesh
        Object_34: THREE.Mesh
        Object_38: THREE.Mesh
        Object_42: THREE.Mesh
        Object_48: THREE.Mesh
        Object_54: THREE.Mesh
        Object_58: THREE.Mesh
        Object_66: THREE.Mesh
        Object_74: THREE.Mesh
        Object_82: THREE.Mesh
        Object_96: THREE.Mesh
        Object_107: THREE.Mesh
        Object_123: THREE.Mesh
        Object_127: THREE.Mesh
    }
    materials: Record<string, THREE.MeshStandardMaterial>
}


export default function MacbookModel16(props: ThreeElements['group']) {
    const {color} = useMacbookStore();
    const { nodes, materials, scene } = useGLTF('/models/macbook-16-transformed.glb') as unknown as GLTFResult

    useEffect(() => {
        scene.traverse((child) => {
            if ((child as THREE.Mesh).isMesh) {
                const mesh = child as THREE.Mesh
                const mat = mesh.material as THREE.MeshStandardMaterial
                if (!noChangeParts.includes(child.name)) {
                    mat.color = new Color(color);
                }
            }
        })
    }, [color, scene])

    const texture = useTexture("/screen.png")
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_10.geometry}
                material={materials.PaletteMaterial001}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_16.geometry}
                material={materials.zhGRTuGrQoJflBD}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_20.geometry}
                material={materials.PaletteMaterial002}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_22.geometry}
                material={materials.lmWQsEjxpsebDlK}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_30.geometry}
                material={materials.LtEafgAVRolQqRw}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_32.geometry}
                material={materials.iyDJFXmHelnMTbD}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_34.geometry}
                material={materials.eJObPwhgFzvfaoZ}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_38.geometry}
                material={materials.nDsMUuDKliqGFdU}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_42.geometry}
                material={materials.CRQixVLpahJzhJc}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_48.geometry}
                material={materials.YYwBgwvcyZVOOAA}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_54.geometry}
                material={materials.SLGkCohDDelqXBu}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_58.geometry}
                material={materials.WnHKXHhScfUbJQi}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_66.geometry}
                material={materials.fNHiBfcxHUJCahl}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_74.geometry}
                material={materials.LpqXZqhaGCeSzdu}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_82.geometry}
                material={materials.gMtYExgrEUqPfln}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_96.geometry}
                material={materials.PaletteMaterial003}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_107.geometry}
                material={materials.JvMFZolVCdpPqjj}
                rotation={[Math.PI / 2, 0, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_123.geometry}
                material={materials.sfCQkHOWyrsLmor}
                rotation={[Math.PI / 2, 0, 0]}
            >
                <meshBasicMaterial map={texture} />
            </mesh>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_127.geometry}
                material={materials.ZCDwChwkbBfITSW}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

useGLTF.preload('/models/macbook-16-transformed.glb')
